storeproject/register/urls.py
from django.urls import path

from register import views


urlpatterns = [

    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('fill',views.fill,name='fill'),
    path('course', views.course, name='course'),
    path('<int:pk>/',views.fillupdate,name='fillupdate'),
    path('newpage',views.newpage,name='newpage'),


]

storeproject/storeapp/urls.py
from django.urls import path

from storeapp import views
app_name='storeapp'
urlpatterns = [

    path('',views.home,name='home'),
]

storeproject/storeproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from register import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('storeapp.urls')),
    path('register/',include('register.urls')),

]
if settings.DEBUG:
             urlpatterns += static(settings.STATIC_URL,
             document_root=settings.STATIC_ROOT)
             urlpatterns += static(settings.MEDIA_URL,
             document_root=settings.MEDIA_ROOT)

storeproject/register/models.py
from django.db import models

# Create your models here

class Department(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Purpose(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class CV(models.Model):
    name=models.CharField(max_length=250)
    dob=models.DateField(auto_now=False,auto_now_add=False)
    age=models.PositiveIntegerField()
    gender=models.CharField(max_length=40)
    mob=models.PositiveIntegerField()
    email=models.EmailField()
    address=models.TextField(max_length=50)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)
    purpose = models.ForeignKey(Purpose, on_delete=models.SET_NULL, blank=True, null=True)
    materials=models.CharField(max_length=100)

    def __str__(self):
        return self.name

storeproject/storeapp/models.py
from django.db import models

# Create your models here.

storeproject/register/forms.py
from django import forms
from .models import CV, Course


Gender= [('Male','Male'),('Female','Female')]
materials=[('Pencil','Pencil'),('debit','debit'),('paper','paper')]
class CVForm(forms.ModelForm):

    gender=forms.ChoiceField(choices=Gender,widget=forms.RadioSelect)
    materials=forms.MultipleChoiceField(choices=materials,widget=forms.CheckboxSelectMultiple)

    class Meta:
        model=CV
        fields=['name','dob','age','gender','mob','email','address','department','course','purpose','materials']
        labels={'name':'Fullname','dob':'Date of Birth','age':'Age','gender':'Gender','mob':'Mobile',
                'email':'EmailID','address':'Address','department':'Department','course':'Course','purpose':'Purpose','materials':'Materials'}



    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = Course.objects.filter(department_id=department_id).all()
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.department.course_set.all()

storeproject/register/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404


from register.forms import CVForm
from register.models import CV, Course


# Create your views here.
def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password = request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
             auth.login(request,user)
             return redirect('newpage')

        else:
            return redirect('login')

    return render(request,"login.html")
def register(request):
    if request.method=='POST':
        username=request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                return redirect("register")
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save();
                return redirect("login")
        else:
            return redirect("register")
        return redirect("/")
    return render (request,"register.html")
def logout(request):
    auth.logout(request)
    return redirect('/')


def fill(request):
    form=CVForm()
    if request.method =='POST':
        form=CVForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Form Submitted Successfully')
            return redirect('fill')
    return render(request,'fill.html',{'form':form})

def fillupdate(request, pk):
    cv = get_object_or_404(CV, pk=pk)
    form = CVForm(instance=cv)
    if request.method == 'POST':
        form = CVForm(request.POST, instance=cv)
        if form.is_valid():
            form.save()
            return redirect('fill', pk=pk)
    return render(request, 'fill.html', {'form': form})



def course(request):
    department_id = request.GET.get('department_id')
    course = Course.objects.filter(department_id=department_id).all()
    return render(request, 'fill2.html', {'course': course})


def newpage(request):
    return render(request,'new page.html')

storeproject/storeapp/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'home.html')

storeproject/templates/fill.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'jquery-ui-timepicker-addon.css' %}">
</head>
<body>
<div class="container text-center mb-5">
    <h1 class="alert-success text center" style="color:red;background-color:aqua;">Fill Form</h1>
    <div class="row">
        <div class="col-sm-12">
            <form  method="post" id="CVForm" data-course-url="{% url 'course' %}"  >
                {% csrf_token %}
                {% for fm in form %}
                <div class="form-group mb-3">
                    {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
                </div>
                {% endfor %}
                <input type="submit" value="Submit" class="btn btn-primary">
                {% if form.non_field_errors %}
                  {% for error in form.non_field_errors %}
                   <p class="alert alert-danger my-3">{{error}}</p>
                  {% endfor %}
                {% endif %}
                <div>
                    <button class="btn btn-primary"><a href="/register/logout" style="color:black;background-color:yellow;">Logout</a></button>
                </div>
                <div>
                    {% for msg in messages %}
                        {{msg}}
                    {% endfor %}
                </div>
                <div>
                    <button class="btn btn-primary"><a href="{% url 'storeapp:home' %}" style="color:red;">Back to Home</a></button>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'jquery-ui.js' %}"></script>
<script src="{% static 'jquery-ui-timepicker-addon.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $( function() {
        $( "#id_dob" ).datepicker({ dateFormat: 'yy-mm-dd'}).attr("autocomplete","off") ;
    });
</script>

<script>
    $("#id_department").change(function () {
        const url = $("#CVForm").attr("data-course-url");  // get the url of the `load_cities` view
        const departmentId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'department_id': departmentId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                console.log(data)
                $("#id_course").html(data);  // replace the contents of the city input with the data that came from the server


                let html_data = '<option value="">---------</option>';
                data.forEach(function (course) {
                    html_data += `<option value="${course.id}">${course.name}</option>`
                });
                console.log(html_data);
                $("#id_course").html(html_data);


            }
        });

    });
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

</body>
</html>

storeproject/templates/fill2.html
<option value="">---------</option>
{% for course in course %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

storeproject/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background-color:aqua;">
<div>
{% include 'navbar.html' %}
</div>
<div class="col-md-12 text-center">
    <h3>Click This <a href="register/login" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Button</a>To Login</h3>
</div>



</body>
</html>

storeproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login page</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">

    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form action="login" method="post">
        {% csrf_token %}
        <h3>Login Here</h3>

        <label >Username</label>
        <input type="text" name="username" placeholder="Username">

        <label >Password</label>
        <input type="password" name="password" placeholder="Password">

        <input  type="submit" value="Submit" class="btn btn-primary " style="color:blue;background-color:yellow;">
        <button class="btn btn-success " style="color:red;background-color:green"><a href="/register/register">Register</a></button>

    </form>

</body>
</html>

  
</body>
</html>

storeproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand"  style="font-size:40px;width:30rem;">DonBosco Store </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a style="color:white;spacing:20px;font-size:20px;width:13rem;" class="nav-link" href="{% url 'storeapp:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a style="color:white;spacing:20px;font-size:20px;width:20rem;" class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Department
        </a>
        <div style="background-color:blue;" class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a style="color:white;font-size:20px;" class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">COMPUTERSCIENCE</a>
          <a style="color:white;font-size:20px;" class="dropdown-item" href="https://en.wikipedia.org/wiki/Science">SCIENCE</a>
          <a style="color:white;font-size:20px;" class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">COMMERCE</a>
          <a style="color:white;font-size:20px;" class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities">HUMANITIES</a>
          <a style="color:white;font-size:20px;" class="dropdown-item" href="https://en.wikipedia.org/wiki/Secondary_School_Leaving_Certificate">SSLC</a>
        </div>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-link" style="color:white;font-size:20px;width:20rem;" ><p>'Hello {{user.username}}'</p></li>
      <li class="nav-item">
        <a style="color:white;font-size:20px;width:20rem;" class="nav-link" href="register/logout">LogOut</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a style="color:white;font-size:20px;width:20rem;" class="nav-link" href="register/register">Register</a>
      </li>
      <li class="nav-item">
        <a style="color:white;font-size:20px;width:20rem;" class="nav-link" href="register/login">LogIn</a>
      </li>
      {% endif %}
    </ul>
  </div>
  </div>
</nav>
<style media="screen">

</style>

storeproject/templates/new page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Page</title>
</head>
<body >
<img src="back.jpg" alt="dummy" style="width:1920px;height:1080">
<div class="container-fluid">
    <div class="col-md-12 text-center">
    <h3>Click This <a href="/register/fill" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Button</a>To fill form</h3>
    </div>
</div>

</body>
</html>

storeproject/templates/register.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Registration page</title>
</head>
<body>

<!DOCTYPE html>
<html lang="en">
<head>

    <title>Login page</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">

    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form action="register" method="post">
        {% csrf_token %}
        <h3>Register Here</h3>

        <label >Username</label>
        <input type="text" name="username" placeholder="Username">

        <label >Password</label>
        <input type="password" name="password" placeholder="Password">

        <label >ConfirmPassword</label>
        <input type="password" name="password1" placeholder="ConfirmPassword">


        <input type="submit" value="Submit" class="btn" style="color:white;background-color:red;">

    </form>
</body>
</html>


</body>
</html>